name: website_learner
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - openai
      - httpx
      - requests
      - beautifulsoup4
      - pytest
